#!/bin/bash 

filelist=`/bin/ls $1`
ERR="Err:This is not a eeprom image file!"

eep_image_file_list=()
i=0
#循环打开操作本目录下所有的文件
for file in $filelist
do
#跳过目录
    if [ -d "${file}" ] 
    then
        continue
    fi
#从文件名获取eeprom的序列号和版本号
    INFO=$(eep_edit_tool ${file} << EOF | sed -n 2p
quit
EOF
)
#筛选出eeprom image文件放入数组
    if [ "${INFO}" != "${ERR}" ]
    then
        eep_image_file_list[$i]=${file}
        let i=i+1
    fi
done

#循环查询eep_image_file_list数组中的eeprom image文件的版本信息
for eep_image_file in ${eep_image_file_list[@]}
do

    VER=$(eep_edit_tool ${eep_image_file} << EOF | grep version:
version
quit
EOF
)
    printf "%-50s\t%s\n" "${eep_image_file}" "${VER}"
done
